# Generated by Django 4.1.5 on 2023-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_services_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=50)),
                ('slider_image', models.ImageField(upload_to='images')),
                ('slider_squ', models.IntegerField()),
            ],
        ),
    ]
